language: bash
services:
- docker
before_install:
- mkdir -p assemblies
script:
- docker run -it --rm -v $(pwd)/:/app mcr.microsoft.com/dotnet/core/sdk:3.1 /app/scripts/build/publish.sh
- ./scripts/build/package.sh
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: VkjSRVs5ZYSYyvWTpBv5yZnrog9FKPdy6iW5OUtCg6Q6Rs4qi4QNlRv9NXXp5zlYFXE2NPAcQVllQG2D/e0X86y/OZHPgkABzIl4ppE3PN0h42QJY7kC9k/CRRBs/osqyuHwmq56vRdbyXlopkReL+s6B19UqdoYXPBmuXuQtSBdzMIzxno3vzFSxQEGulfVJTAKStvXQpY7cyy8FOcu5vmQ0MParArFibiHGcJrCyu9lATg0Ko32f0m2D8XuONiC9uMgckr2hie415RjccsxusNSOHcaDfxNt5FGAj9YJrG+u0lV7YCSzAYdIJKZShpmGxBRSZZlLUCT5kHZwa57uKMv9tbuyFDE3GYFqn4+kRTjIrsw33ZGMgTDC8prPybvlF7czYT/6aZP2Y/PPLgVb8+1TAOrR5IZg5SA0RSaWVDSv1hU+0ZIo2CqkUXsuzLU1N1/YoHclMgmMFgLzvYlRGbchehPSdPgzm3DoUIwqML1EVBcWIsnpZ5/ktHe/qJtrHNiqAziWPBBrSBMpoNx1ZxKo7dLAJcSuy157CSUH09mu5M+Wc675vBgsHS0ysW1ad0u3TYFkN7R5KxwGmlIaICZqcuNvE2tzvl1csyvHxun8XBTIKAyyLVE6fijZtm0BB1kHn2wq4y3brYaTdjG4OMbfBkoEPTd6EvzoikVz0=
  file:
    - "./assemblies/linux-x64.tgz"
    - "./assemblies/osx-x64.tgz"
    - "./assemblies/win-x64.tgz"
    - "./assemblies/win-x86.tgz"
  on:
    repo: tsqllint/tsqllint
    tags: true
  skip_cleanup: 'true'
